feat(react-graphql-types): add self package to react dev dependencies
vtex/toolbelt pull request #1036
Opened 2021-03-05 19:27 UTC by gsasouza

#### What is the purpose of this pull request?

Add self (app you are setuping) package to react app dev dependencies

#### What problem is this solving?

This allows the use of graphql operation types, by importing the app types

#### How should this be manually tested?
 - npm link package
 - vtex setup on your app
 - check react package devDependecies, it should include self package

#### Screenshots or example usage

#### Types of changes
- [ ] Refactor (non-breaking change that only makes the code better)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

#### Chores checklist
- [x] Update `CHANGELOG.md`

2021-03-05 20:25 UTC, klzns requested changes

2021-03-05 20:25 UTC, klzns commented on CHANGELOG.md
> +- Add self package to react packages as devDependency
```suggestion
### Changed
- Add self package to react packages as devDependency
```

2021-03-10 20:32 UTC, klzns approved these changes

2021-03-11 16:23 UTC, klzns approved these changes

2021-03-16 17:07 UTC, Klynger approved these changes

2021-03-17 21:52 UTC, dhasuda approved these changes
LGTM! I kindly ask you to do the same modifications to the `3.x` branch, that soon will be de default branch of toolbelt (we're only finishing some work to release the new major)

2021-03-18 17:16 UTC, merged